configuration: Release

cache:
- packages -> **\packages.config
- '%USERPROFILE%\.nuget\packages -> **\project.json'

environment:
  nugetVersion: 1.0.0

version: $(nugetVersion).{build}

build_script:
- ps: .\build.ps1
test: off

artifacts:
- path: artifacts/packages/*.nupkg


deploy:
- provider: NuGet
  server: https://www.myget.org/F/linq2db/api/v2
  api_key:
    secure: LDw0jeA1Yo3R4/TKv2kmlgJR8dTT6Wun2MONq3uDvtVQJG4LOU9LjvVTAc7IgRfm
  skip_symbols: true
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: oTYw2IwTnz4qMD8c/MR/6mo+Nx3wa5Pp8MYfsKBCKCVuU6QCHlj+6QMXpnQses8G
  on:
    branch: release


#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/